name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: "pip" # Caches pip dependencies to speed up future CI runs
      - name: Install package
        run: pip install -e ".[dev,docs]"
      - name: Pytest
        run: pytest
      - name: BasedPyright
        run: basedpyright
      - name: Zensical strict build
        run: zensical build --strict
